### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by fredym** [QMDevTeam/QMPDA#10]
We need a method to pass through a Questionnaire without allowing the user to make changes to the answers.

A visual cue in the screen will let the user that Read only mode is on.

Validations should be turned off but Checkpoints will still be observed.

Thanks to the layered code, this is not that big of a change. Most of the work will be turn read only the controls of the screen with the switch of a property.

**Comment by gerardlopez2001** [comment]
Moved to Trello: https://trello.com/c/GwdAtbB1
