### ISSUE TITLE
Migrate the code to Visual Studio 2008

### ISSUE THREAD

**Issue by fredym** [QMDevTeam/QMPDA#3]
We have identified that the current development environment (Visual Studio 2005) is too old to find support, proper documentation and to reproduce easily. In fact, it has known issues when installing in Windows 7 to develop software for mobile devices using Windows Mobile 5.0

In addition, currently it is necessary to avoid installing the SQL Server Express 2005 that comes with Visual Studio 2005 and separately installing SQL Server Express 2008 in order to have development support for SQL CE 3.5. On the other side, eventually we are going to replace SQL CE with SQLite.

We plan to simplify the setup of the development environment by migrating to Visual Studio 2008 SP1 and therefore, alignt the versions of Visual Studio, SQL Server, SQL CE and the .NET Framework.

**Comment by gerardlopez2001** [comment]
Moved to Trello:  https://trello.com/c/8XwsUzdp
