### ISSUE TITLE
Remove OpenNETCF dependency

### ISSUE THREAD

**Issue by fredym** [QMDevTeam/QMPDA#4]
Why do we need OpenNETCF?
- Provides a Checkbox control with support for multiple lines of text for each checkbox, although I think this is no longer needed because Manuel developed a custom control.
- Application configuration file (App.config)
- Provides a function to calculate the dimensions of a Label control in order to display a given text, font y font size.

If these functionality is already provided by the .NET Compact Framework 3.5, then we can remove this dependency.

**Comment by gerardlopez2001** [comment]
Moved to Trello:  https://trello.com/c/PJdaThLa
