### ISSUE TITLE
Replace SQL CE with SQLite

### ISSUE THREAD

**Issue by fredym** [QMDevTeam/QMPDA#6]
Currently the data access layer uses SQL CE 3.5 to store questionnaire configuration data and answers data.

Considering that the PDA Engine must use data files compatible with the Android Engine and that Android is shipped with SQLite, it is necessary to replace this component with SQLite.

It is still a matter of discussion what version of SQLite will be used. What version is available for Windows Mobile 5.0? What version is shipped with Android?

**Comment by gerardlopez2001** [comment]
Moved to Trello:  https://trello.com/c/ZSGInFAl
